export const mockMovies = [
  {
    id: 1,
    title: "Inception",
    name: "Inception",
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    vote_average: 8.8,
    release_date: "2010-07-15",
    first_air_date: "2010-07-15",
  },
  {
    id: 2,
    title: "Interstellar",
    name: "Interstellar",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/xJHbUAKC5h8iU2yqgIfK3MvH9uW.jpg",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    vote_average: 8.6,
    release_date: "2014-11-05",
  },
  {
    id: 3,
    title: "The Dark Knight",
    name: "The Dark Knight",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/oqP1qEZccq5AD9TVTIaO6IGUj7o.jpg",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    vote_average: 9.0,
    release_date: "2008-07-16",
  },
  {
    id: 4,
    title: "Avatar",
    name: "Avatar",
    poster_path: "/kyeqWdyAItLPEK8HPEz5E5A8Q6U.jpg",
    backdrop_path: "/vL5LR0nK8p6C4P3K1hL6yNhmSih.jpg",
    overview: "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission...",
    vote_average: 7.5,
    release_date: "2009-12-15",
  },
  {
    id: 5,
    title: "Spider-Man: No Way Home",
    name: "Spider-Man: No Way Home",
    poster_path: "/1g0dhYtq4irTY1R80vfaSaG5L.jpg",
    backdrop_path: "/iQFcwSd0A03z3Kk8G0cE90iK8eE.jpg",
    overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero.",
    vote_average: 8.0,
    release_date: "2021-12-15",
  },
  {
    id: 6,
    title: "Avengers: Endgame",
    name: "Avengers: Endgame",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    overview: "After the devastating events of Infinity War, the universe is in ruins...",
    vote_average: 8.3,
    release_date: "2019-04-24",
  }
];

export const mockShows = [
  {
    id: 101,
    title: "Breaking Bad",
    name: "Breaking Bad",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRkE1.jpg",
    backdrop_path: "/aB1EAZhLwO4OtsP10xEX6gEMO5V.jpg",
    overview: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine...",
    vote_average: 9.2,
    first_air_date: "2008-01-20",
  },
  {
    id: 102,
    title: "Stranger Things",
    name: "Stranger Things",
    poster_path: "/49WJfeN0moxb9IPfGn8R2P8jR3C.jpg",
    backdrop_path: "/56v2KjBlU4Xa0661KqA2Nn26A1.jpg",
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    vote_average: 8.6,
    first_air_date: "2016-07-15",
  },
  {
    id: 103,
    title: "Game of Thrones",
    name: "Game of Thrones",
    poster_path: "/szDziwDtsE58zR470WmtRAn42rA.jpg",
    backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    overview: "Seven noble families fight for control of the mythical land of Westeros.",
    vote_average: 8.4,
    first_air_date: "2011-04-17",
  },
  {
    id: 104,
    title: "The Mandalorian",
    name: "The Mandalorian",
    poster_path: "/sWgBv7LV2PRoQgZx5v8d1x8yH5v.jpg",
    backdrop_path: "/8BwD24dI93pI042aYscKx8OtvCj.jpg",
    overview: "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy...",
    vote_average: 8.4,
    first_air_date: "2019-11-12",
  }
];
